-- CHAR and VARCHAR
-- INT, SMALLINT, TINYINT, MEDIUMINT, BIGINT
-- DECIMAL
-- FLOAT and DOUBLE
-- DATE and TIME and DATETIME
-- CURDATE, CURTIME, NOW
-- DAYOFMONTH, DAYOFWEEK, DAYOFYEAR, MONTHNAME, YEAR
-- HOUR, MINUTE, SECOND
-- DATE_FORMAT, TIME_FORMAT

